version: '3.8'
services:
  app:
    build: .
    ports:
      - "8081:8081"
    depends_on:
      - db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3307/meta-verso?allowPublicKeyRetrieval\=true&useSSL\=false&serverTimezone\=UTC
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=!LH%2Avqc2%mWb7lF29#

  db:
    image: mysql:8.0
    container_name: db
    ports:
      - "3307:3307"
    environment:
      - MYSQL_ROOT_PASSWORD=!LH%2Avqc2%mWb7lF29#
      - MYSQL_DATABASE=meta-verso
      - MYSQL_USER=root
      - MYSQL_PASSWORD=!LH%2Avqc2%mWb7lF29#
    volumes:
      - db_data:/var/lib/mysql
volumes:
  db_data: