spring.application.name=udlaverso

server.port=8081

# Configuración de la base de datos MySQL

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Configuración de JPA/Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect


scalar.path=/docs


# Configuración de MinIO
minio.endpoint=https://meta-verso-minio.b0falx.easypanel.host
minio.access-key=admin
minio.secret-key=!Admin123
minio.secure=true

